before:
  hooks:
    - go mod download
builds:
- id: registry-check
  binary: registry-check
  main: ./cmd/registry-check/main.go
  env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  ignore:
    - goarch: arm64
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }}
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
    - go mod tidy
archives:
  - id: tgz
    format: tar.gz
    replacements:
        darwin: macOS
    format_overrides:
        - goos: windows
          format: zip
signs:
  - artifacts: checksum
